NEWS_API_COUNTRY_CODES = (
    {"country": "Argentina", "code": "ar"},
    {"country": "Australia", "code": "au"},
    {"country": "Austria", "code": "at"},
    {"country": "Belgium", "code": "be"},
    {"country": "Brazil", "code": "br"},
    {"country": "Bulgaria", "code": "bg"},
    {"country": "Canada", "code": "ca"},
    {"country": "China", "code": "cn"},
    {"country": "Colombia", "code": "co"},
    {"country": "Cuba", "code": "cu"},
    {"country": "Czech Republic", "code": "cz"},
    {"country": "Egypt", "code": "eg"},
    {"country": "France", "code": "fr"},
    {"country": "Germany", "code": "de"},
    {"country": "Greece", "code": "gr"},
    {"country": "Hong Kong", "code": "hk"},
    {"country": "Hungary", "code": "hu"},
    {"country": "India", "code": "in"},
    {"country": "Indonesia", "code": "id"},
    {"country": "Ireland", "code": "ie"},
    {"country": "Israel", "code": "il"},
    {"country": "Italy", "code": "it"},
    {"country": "Japan", "code": "jp"},
    {"country": "Latvia", "code": "lv"},
    {"country": "Lithuania", "code": "lt"},
    {"country": "Malaysia", "code": "my"},
    {"country": "Mexico", "code": "mx"},
    {"country": "Morocco", "code": "ma"},
    {"country": "Netherlands", "code": "nl"},
    {"country": "New Zealand", "code": "nz"},
    {"country": "Nigeria", "code": "ng"},
    {"country": "Norway", "code": "no"},
    {"country": "Philippines", "code": "ph"},
    {"country": "Poland", "code": "pl"},
    {"country": "Portugal", "code": "pt"},
    {"country": "Romania", "code": "ro"},
    {"country": "Russia", "code": "ru"},
    {"country": "Saudi Arabia", "code": "sa"},
    {"country": "Serbia", "code": "rs"},
    {"country": "Singapore", "code": "sg"},
    {"country": "Slovakia", "code": "sk"},
    {"country": "Slovenia", "code": "si"},
    {"country": "South Africa", "code": "za"},
    {"country": "South Korea", "code": "kr"},
    {"country": "Sweden", "code": "se"},
    {"country": "Switzerland", "code": "ch"},
    {"country": "Taiwan", "code": "tw"},
    {"country": "Thailand", "code": "th"},
    {"country": "Turkey", "code": "tr"},
    {"country": "UAE", "code": "ae"},
    {"country": "Ukraine", "code": "ua"},
    {"country": "United Kingdom", "code": "gb"},
    {"country": "United States", "code": "us"},
    {"country": "Venezuela", "code": "ve"},
)
